<a href="https://colab.research.google.com/github/mouha-ndour/PyTorch-fundamentals/blob/main/PyTorch_in_One_Hour.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**I. WAHT IS PYTORCH ?**

- An open source Pyhon-based deep learning library.
- Pytorch has been the most widely used deep learning library for research papers since 2019 by a wide margin.
- One of the reasons Pytorch is so popular is its user-friendly interface and efficiency.

**1. The three core components of PyTorch**

- Tensor library: that extends the concept of aaray-oriented programming library NumPy with the additional feature of accelerated computation on GPUs, thus providing a seamless swith CPUs and GPUs.
- Automatic differentiation engine: alse known as autograd, which enables the automatic computation of gradients for tensor operations, simplifying backpropageion and model optimization.

In [1]:
# Installing PyTorch

# A leaner version that only supports CPU computing and a
# version that supports both CPU and GPU computing.

!pip install torch
import torch
torch.__version__

'2.8.0+cu126'

**II. Understanding tensors**

Tensors represent a mathematical concept that generalizes vectorss and matrices to potentially higher dimensions. Tensors are mathemaical objects that can be characterized by their order (or rank), which provides the number of dimensions

In [10]:
# Scalars, vectors, matices, and tensors

# We can create objects of PyTORCH's Tensor class using the orch.tensor function as follows:

import torch

# Create a 0D tensor (scaalar) from a Python integer
tensor0d=torch.tensor(1)

# Create a 1D tensor(vector) from a python list
tensor1d=torch.tensor([1,2,3])

# Create a 2D tensor from a nested Python list
tensor2d=torch.tensor([[1,2], [3,4]])

# create a 3D tensor from a nested Python list
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])


tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [13]:
# Tensor data types

tensor1d=torch.tensor([1,2,3])
print(tensor1d.dtype)

# If we create tensors from Python floats, PyTorch creates tensors with a 32-bit precision
# by default, as we can see below.
floatvec=torch.tensor([1.0,2.0,3.0])
print(floatvec.dtype)

torch.int64
torch.float32


**III. Tensor Data Types**

PyTorch tensors can hold data of various types. The choice of data type is crucial as it affects memory consumption, computational speed, and precision. PyTorch supports several data types, including:

*   `torch.float32` or `torch.float`: Standard floating-point numbers.
*   `torch.float64` or `torch.double`: Double-precision floating-point numbers.
*   `torch.int8`: Signed 8-bit integers.
*   `torch.int16` or `torch.short`: Signed 16-bit integers.
*   `torch.int32` or `torch.int`: Signed 32-bit integers.
*   `torch.int64` or `torch.long`: Signed 64-bit integers.
*   `torch.bool`: Boolean values (True/False).

By default, PyTorch operations often use `torch.float32` for floating-point tensors and `torch.int64` for integer tensors.

You can check the data type of a tensor using the `.dtype` attribute and change it using the `.to()` method or `.type()` method.

In [12]:
import torch

# Create a tensor with default data type (float32)
float_tensor = torch.tensor([1.0, 2.0, 3.0])
print(f"Default float tensor: {float_tensor} | Data type: {float_tensor.dtype}")

# Create an integer tensor with default data type (int64)
int_tensor = torch.tensor([1, 2, 3])
print(f"Default integer tensor: {int_tensor} | Data type: {int_tensor.dtype}")

# Specify a data type during creation
int16_tensor = torch.tensor([1, 2, 3], dtype=torch.int16)
print(f"Int16 tensor: {int16_tensor} | Data type: {int16_tensor.dtype}")

# Change the data type using .to()
float64_tensor = float_tensor.to(torch.float64)
print(f"Float64 tensor: {float64_tensor} | Data type: {float64_tensor.dtype}")

# Change the data type using .type()
int_from_float = float_tensor.type(torch.int32)
print(f"Int32 tensor from float: {int_from_float} | Data type: {int_from_float.dtype}")

# Create a boolean tensor
bool_tensor = torch.tensor([True, False, True])
print(f"Boolean tensor: {bool_tensor} | Data type: {bool_tensor.dtype}")

Default float tensor: tensor([1., 2., 3.]) | Data type: torch.float32
Default integer tensor: tensor([1, 2, 3]) | Data type: torch.int64
Int16 tensor: tensor([1, 2, 3], dtype=torch.int16) | Data type: torch.int16
Float64 tensor: tensor([1., 2., 3.], dtype=torch.float64) | Data type: torch.float64
Int32 tensor from float: tensor([1, 2, 3], dtype=torch.int32) | Data type: torch.int32
Boolean tensor: tensor([ True, False,  True]) | Data type: torch.bool


In [21]:
# Common PyTorch tensor operations

tensor2d=torch.tensor([[1,2,3], [4,5,6]])
tensor2d



tensor([[1, 2, 3],
        [4, 5, 6]])

In [26]:
# The .shape attribute allows us to access the shape of a tensor
print(tensor2d.shape)

# Note that the more common command for reshaping tensors in PyTorch is
# .view
tensor2d.view(3,2)

torch.Size([2, 3])


tensor([[1, 2],
        [3, 4],
        [5, 6]])