<a href="https://colab.research.google.com/github/mouha-ndour/PyTorch-fundamentals/blob/main/PyTorch_in_One_Hour.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**I. WAHT IS PYTORCH ?**

- An open source Pyhon-based deep learning library.
- Pytorch has been the most widely used deep learning library for research papers since 2019 by a wide margin.
- One of the reasons Pytorch is so popular is its user-friendly interface and efficiency.

**1. The three core components of PyTorch**

- Tensor library: that extends the concept of aaray-oriented programming library NumPy with the additional feature of accelerated computation on GPUs, thus providing a seamless swith CPUs and GPUs.
- Automatic differentiation engine: alse known as autograd, which enables the automatic computation of gradients for tensor operations, simplifying backpropageion and model optimization.

In [1]:
# Installing PyTorch

# A leaner version that only supports CPU computing and a
# version that supports both CPU and GPU computing.

!pip install torch
import torch
torch.__version__

'2.8.0+cu126'

**II. Understanding tensors**

Tensors represent a mathematical concept that generalizes vectorss and matrices to potentially higher dimensions. Tensors are mathemaical objects that can be characterized by their order (or rank), which provides the number of dimensions

In [2]:
# Scalars, vectors, matices, and tensors

# We can create objects of PyTORCH's Tensor class using the orch.tensor function as follows:

import torch

# Create a 0D tensor (scaalar) from a Python integer
tensor0d=torch.tensor(1)

# Create a 1D tensor(vector) from a python list
tensor1d=torch.tensor([1,2,3])

# Create a 2D tensor from a nested Python list
tensor2d=torch.tensor([[1,2], [3,4]])

# create a 3D tensor from a nested Python list
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])


In [3]:
# Tensor data types

tensor1d=torch.tensor([1,2,3])
print(tensor1d.dtype)

# If we create tensors from Python floats, PyTorch creates tensors with a 32-bit precision
# by default, as we can see below.
floatvec=torch.tensor([1.0,2.0,3.0])
print(floatvec.dtype)

torch.int64
torch.float32


**III. Tensor Data Types**

PyTorch tensors can hold data of various types. The choice of data type is crucial as it affects memory consumption, computational speed, and precision. PyTorch supports several data types, including:

*   `torch.float32` or `torch.float`: Standard floating-point numbers.
*   `torch.float64` or `torch.double`: Double-precision floating-point numbers.
*   `torch.int8`: Signed 8-bit integers.
*   `torch.int16` or `torch.short`: Signed 16-bit integers.
*   `torch.int32` or `torch.int`: Signed 32-bit integers.
*   `torch.int64` or `torch.long`: Signed 64-bit integers.
*   `torch.bool`: Boolean values (True/False).

By default, PyTorch operations often use `torch.float32` for floating-point tensors and `torch.int64` for integer tensors.

You can check the data type of a tensor using the `.dtype` attribute and change it using the `.to()` method or `.type()` method.

In [4]:
import torch

# Create a tensor with default data type (float32)
float_tensor = torch.tensor([1.0, 2.0, 3.0])
print(f"Default float tensor: {float_tensor} | Data type: {float_tensor.dtype}")

# Create an integer tensor with default data type (int64)
int_tensor = torch.tensor([1, 2, 3])
print(f"Default integer tensor: {int_tensor} | Data type: {int_tensor.dtype}")

# Specify a data type during creation
int16_tensor = torch.tensor([1, 2, 3], dtype=torch.int16)
print(f"Int16 tensor: {int16_tensor} | Data type: {int16_tensor.dtype}")

# Change the data type using .to()
float64_tensor = float_tensor.to(torch.float64)
print(f"Float64 tensor: {float64_tensor} | Data type: {float64_tensor.dtype}")

# Change the data type using .type()
int_from_float = float_tensor.type(torch.int32)
print(f"Int32 tensor from float: {int_from_float} | Data type: {int_from_float.dtype}")

# Create a boolean tensor
bool_tensor = torch.tensor([True, False, True])
print(f"Boolean tensor: {bool_tensor} | Data type: {bool_tensor.dtype}")

Default float tensor: tensor([1., 2., 3.]) | Data type: torch.float32
Default integer tensor: tensor([1, 2, 3]) | Data type: torch.int64
Int16 tensor: tensor([1, 2, 3], dtype=torch.int16) | Data type: torch.int16
Float64 tensor: tensor([1., 2., 3.], dtype=torch.float64) | Data type: torch.float64
Int32 tensor from float: tensor([1, 2, 3], dtype=torch.int32) | Data type: torch.int32
Boolean tensor: tensor([ True, False,  True]) | Data type: torch.bool


In [5]:
# Common PyTorch tensor operations

tensor2d=torch.tensor([[1,2,3], [4,5,6]])
tensor2d



tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
# The .shape attribute allows us to access the shape of a tensor
print(tensor2d.shape)

# Note that the more common command for reshaping tensors in PyTorch is
# .view
tensor2d.view(3,2)

torch.Size([2, 3])


tensor([[1, 2],
        [3, 4],
        [5, 6]])

**IV- SEEING MODELS AS COMPUTATION GRAPHS**


In the previous section, we covered one of the major three components of PyTorch, namely, its tensor library. Next in line is PyTorch's automatic differenctiation engine, also known as autograd. Before we dive deeper into computing gradients in the next section, let's define the concept of a computational graph.

A computational graph is a directed graph that allows us to express andvisualize mathematical expressions. In the context of deep learning, a computation graph lays ou the sequence of calculations neede to compute the output of a neural networks.

Let's look at a concrete example to illustrate the concept of a computation graph: a simple logistic regression classifier (which can be seen as single layer neural network).

In [7]:
import torch.nn.functional as F

y=torch.tensor([1.0])
x1=torch.tensor([1.1])
w1=torch.tensor([2.2])
b=torch.tensor([0.0])

z=x1*w1 + b # net input
a=torch.sigmoid(z) # activation & output
loss=F.binary_cross_entropy(a, y)
print(loss)



tensor(0.0852)


**V. AUTOMATIC DIFFERENTIATION MADE EASY**


- requires_grad := In the previous section, we introduced the concept of computation graphs. If we carry out computations in PyTorch, it will build such a graph internally by default if one of its terminal nodes has the requires_grad attribute set to True. This is useful if we want to compute gradients. Gradients are required when training neural networks via the popular backpropagation algorithm, which can be thought of as an implementation of the chain rule from calculus for neural networks

- retain_graph :=By default, PyTorch destroys the computation graph after calculating the gradients to free memory. However, since we are going to reuse this computation graph shortly, we set retain_graph=True so that it stays in memory.

- .backward :=
- .grad := We can call .backward on the loss, and PyTorch will compute the gradients of all the leaf nodes in the graph, which will be stored via the tensors’ .grad attributes:

In [8]:
import torch.nn.functional as F
from torch.autograd import grad

y=torch.tensor([1.0])
x1=torch.tensor([1.1])
w1=torch.tensor([2.2], requires_grad=True)
b=torch.tensor([0.0], requires_grad=True)

z=x1*w1 + b
a=torch.sigmoid(z)

loss=F.binary_cross_entropy(a, y)

grad_L_w1= grad(loss, w1, retain_graph=True)
grad_L_b= grad(loss, b, retain_graph=True)



In [9]:
loss.backward()

print(w1.grad)
print(b.grad)

tensor([-0.0898])
tensor([-0.0817])


**VI. IMPLEMENTING MULTILAYER NEURAL NETWORKS**



In [10]:
class NeuralNetwork(torch.nn.Module):
  def __init__(self, num_inputs, num_outputs):
    super().__init__()

    self.layers = torch.nn.Sequential(

                                      # 1st hidden layer
                                      torch.nn.Linear(num_inputs, 30),
                                      torch.nn.ReLU(),

                                      # 2nd hidden layer
                                      torch.nn.Linear(30, 20),
                                      torch.nn.ReLU(),

                                      # output layer
                                      torch.nn.Linear(20, num_outputs),

       )

  def forward(self, x):
    logits = self.layers(x)
    return logits

In [11]:
# We can then instantiate a new neural network object as follows:
model = NeuralNetwork(50, 3)

# Let's see the summary of its structure
print(model)

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)


In [12]:
# Now let's check the total number of trainable parameters of this model
num_params = sum(
    p.numel() for p in model.parameters() if p.requires_grad
)

print("Total number of trainable model parameters:", num_params)

Total number of trainable model parameters: 2213


In [13]:
# Based on the print(model) call we executed above, we can see that the first
# Linear layer is at index position 0 in the layers attribute. We can access the corresponding weight parameter matrix as follows:

print(model.layers[0].weight)
print(model.layers[0].weight.shape)

Parameter containing:
tensor([[-0.0456, -0.0141,  0.0761,  ..., -0.0324, -0.0042,  0.1161],
        [ 0.0323,  0.1321, -0.1145,  ...,  0.0313, -0.0374,  0.0726],
        [ 0.0972, -0.0297, -0.0370,  ...,  0.0319, -0.1087,  0.0325],
        ...,
        [-0.1201,  0.0165, -0.0224,  ...,  0.1244, -0.1190, -0.0560],
        [ 0.0922, -0.1121,  0.0968,  ..., -0.0456,  0.0201,  0.0638],
        [-0.0840,  0.0378,  0.1035,  ..., -0.0011,  0.1358, -0.1325]],
       requires_grad=True)
torch.Size([30, 50])


In [14]:
torch.manual_seed(123)

model = NeuralNetwork(50, 3)
print(model.layers[0].weight)

Parameter containing:
tensor([[-0.0577,  0.0047, -0.0702,  ...,  0.0222,  0.1260,  0.0865],
        [ 0.0502,  0.0307,  0.0333,  ...,  0.0951,  0.1134, -0.0297],
        [ 0.1077, -0.1108,  0.0122,  ...,  0.0108, -0.1049, -0.1063],
        ...,
        [-0.0787,  0.1259,  0.0803,  ...,  0.1218,  0.1303, -0.1351],
        [ 0.1359,  0.0175, -0.0673,  ...,  0.0674,  0.0676,  0.1058],
        [ 0.0790,  0.1343, -0.0293,  ...,  0.0344, -0.0971, -0.0509]],
       requires_grad=True)


In [15]:
torch.manual_seed(123)

X=torch.rand((1, 50))
out=model(X)
print(out)

tensor([[-0.1262,  0.1080, -0.1792]], grad_fn=<AddmmBackward0>)


In [16]:
with torch.no_grad():
  out = model(X)
print(out)

tensor([[-0.1262,  0.1080, -0.1792]])


In [17]:
with torch.no_grad():
  out = torch.softmax(model(X), dim=1)
print(out)

tensor([[0.3113, 0.3934, 0.2952]])


Let’s start by creating a simple toy dataset of five training examples with two features each. Accompanying the training examples, we also create a tensor containing the corresponding class labels: three examples belong to class 0, and two examples belong to class 1. In addition, we also make a test set consisting of two entries. The code to create this dataset is shown below.

In [18]:

X_train = torch.tensor([
    [-1.2, 3.1],
    [-0.9, 2.9],
    [-0.5, 2.6],
    [2.3, -1.1],
    [2.7, -1.5]
])

y_train = torch.tensor([0, 0, 0, 1, 1])

X_test = torch.tensor([
    [-0.8, 2.8],
    [2.6, -1.6],
])

y_test = torch.tensor([0, 1])

Next, wee create a custom dataset class, ToyDataset, by subclassing from PyTorch'sDataset parent class, as shown below.

In [24]:
from torch.utils.data import Dataset

class ToyDataset(Dataset):
  def __init__(self, X, y):
    self.features = X
    self.labels = y

  def __getitem__(self, index):
    one_x = self.features[index]
    one_y = self.labels[index]
    return one_x, one_y

  def __len__(self):
    return self.labels.shape[0]

train_ds = ToyDataset(X_train, y_train)
test_ds = ToyDataset(X_test, y_test)

This custom ToyDataset class’s purpose is to use it to instantiate a PyTorch DataLoader. But before we get to this step, let’s briefly go over the general structure of the ToyDataset code.

In PyTorch, the three main components of a custom Dataset class are the __init__ constructor, the __getitem__ method, and the __len__ method, as shown in code ToyDataset code above.

In the __init__ method, we set up attributes that we can access later in the __getitem__ and __len__ methods. This could be file paths, file objects, database connectors, and so on. Since we created a tensor dataset that sits in memory, we are simply assigning X and y to these attributes, which are placeholders for our tensor objects.

In the __getitem__ method, we define instructions for returning exactly one item from the dataset via an index. This means the features and the class label corresponding to a single training example or test instance. (The data loader will provide this index, which we will cover shortly.)

Finally, the __len__ method contains instructions for retrieving the length of the dataset. Here, we use the .shape attribute of a tensor to return the number of rows in the feature array. In the case of the training dataset, we have five rows, which we can double-check as follows:

In [26]:
from torch.utils.data import DataLoader

torch.manual_seed(123)

train_loader = DataLoader(
    dataset=train_ds,
    batch_size=2,
    shuffle=True,
    num_workers=0
)

In [28]:
from torch.utils.data import DataLoader

torch.manual_seed(123)

test_loader=DataLoader(
    dataset=test_ds,
    batch_size=2,
    shuffle=True,
    num_workers=0
)